### ISSUE TITLE
Los Chicos No Saben Explorar

### ISSUE THREAD

**Issue by Secreto31126** [Secreto31126/Digital-House-Answers#1]
Si llegaste hasta acá, parece que no te afecta a vos.

Bien por experimentar

**Comment by Secreto31126** [comment]
Testing...

**Comment by Secreto31126** [comment]
I need people to see this 🤷‍♂️

**Comment by Secreto31126** [comment]
@Secreto31126 HIIII!

**Comment by adelehk** [comment]
hola, el ejercicio ; Actividad Integradora
En este ejercicio tienes toda la estructura en la que vienes trabajando pero sin su contenido. Prueba escribir tu propio tutorial.

¿Que sabes hacer? ¿Cómo podrías guiar a un compañero o compañera para que aprenda algo?

¡Intentalo! El sitio se ve así:

Lo tenes?

Gracias

**Comment by Secreto31126** [comment]
Hola @adelehk 👋.

Si crees que hay un error en el código te recomiendo crear un nuevo issue y ser un poco más específico de dónde está el problema (hay muchas actividades integradoras, dame un link a una carpeta en específica 😁), o si te atrevés podés crear una nueva rama y corregirlo vos, después yo revisaré que esté todo bien y lo actualizo.

Una pregunta, ¿Te sirven las respuestas? Porque algo que siempre dudé es si todos tenían los mismos ejercicios en Digital, sin importar el colegio o el curso. Los archivos están ordenados para que sea más fácil de entender para mis compañeros, pero si son las mismas unidades para todos podría considerar reorganizarlo.

Gracias.

**Comment by adelehk** [comment]
Mi hija esta usando el playground y hay actividades que no en tendemos.Lo que publicaste es excelente!!!!! 😊Te puedo pasar (por si los tenes) los ejercicios que nos faltan?Aguardo una respuesta.Mil gracias.
    El lunes, 30 de noviembre de 2020 15:13:30 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 


Hola @adelehk 👋 .

Si crees que hay un error en el código te recomiendo crear un nuevo issue y ser un poco más específico de dónde está el problema (hay muchas actividades integradoras, dame un link a una carpeta en específica 😁 ), o si te atrevés podés crear una nueva rama y corregirlo vos, después yo revisaré que esté todo bien y lo actualizo.

Una pregunta, ¿Te sirven las respuestas? Porque algo que siempre dudé es si todos tenían los mismos ejercicios en Digital, sin importar el colegio o el curso. Los archivos están ordenados para que sea más fácil de entender para mis compañeros, pero si son las mismas unidades para todos podría considerar reorganizarlo.

Gracias.

**Comment by Secreto31126** [comment]
@adelehk con gusto, me divierte programar. Pasame las consignas que te falten y te digo si ya las tengo cargadas, o sino te paso las respuestas y algunas explicaciones para que puedan ir entendiendo.

**Comment by adelehk** [comment]
Hola!!!!!! sos un re genio, te agradezco muchísimo el buen gesto que tenes.  Te paso las consignas, quizá las subiste, yo no las encontré. Mil millones de gracias!

Clase 9 - Encabezados, párrafos y listasClase 10 - Encabezados, párrafos y listasClase 11 - Selectores - actividad Actividad 02/Actividad 03Clase 12 - Selectores - Actividad IntegradoraClase 14 - Recursos de comunicación - Actividad IntegradoraClase 15 - Rutas con imágenes y videos - Actividad 04 - Actividad IntegradoraClase 18 - Diseño de banner - Actividad IntegradoraClase 19 - Enlaces - Actividad Integradora - CuestionarioClase 21 - Presentación del Proyecto / Div - Modelo de caja - Actividad 01 - Actividad 02 - Actividad 03 - Actividad 04Actividad IntegradoraClase 22 - Propiedades de CSS: Fondos - Actividad 01 Actividad 02 Actividad 03 Actividad 04 Actividad Integradora
Yo ayudo a mi hija con esto y como ya están por terminar las clases les están pidiendo que tengan todo completo, pero ya no puedo ayudarla porque no entiendo casi nada. Vuelvo a agradecerte!Saludos.    El lunes, 30 de noviembre de 2020 21:54:30 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 


@adelehk con gusto, me divierte programar. Pasame las consignas que te falten y te digo si ya las tengo cargadas, o sino te paso las respuestas y algunas explicaciones para que puedan ir entendiendo.

**Comment by Secreto31126** [comment]
@adelehk una pregunta, ¿Para la [Clase 9 y 10](https://github.com/Secreto31126/Digital-House-Answers/tree/master/4A/Headings%2C%20paragraphs%20and%20lists), la [Clase 11 y 12](https://github.com/Secreto31126/Digital-House-Answers/tree/master/4A/Selectors) y para la [Clase 19](https://github.com/Secreto31126/Digital-House-Answers/tree/master/4A/Links) estas respuestas no les sirven?

Como ya dije antes, no tengo forma de saber de que las clases estén estructuradas de la misma forma para todos en el Playground, e incluso no me sorprendería si ustedes tienen ejercicios que yo nunca ví, y viceversa.

Del resto de las clases que no mencioné estoy seguro que no las tengo en el Playground, así que no sé qué piden los enunciados. No tengo problemas en hacer algunos para ustedes para que vean cómo se resuelven, aunque voy a necesitar que me pasen las consignas completas de cada actividad y cualquier cosa que incluya el editor de código. Si te interesa podés escribir los enunciados en comentarios separados así no se mezclan los ejercicios.

**Comment by adelehk** [comment]
Hola!!!!
Mil gracias por ayudarnos!Si, claro te paso los enunciados tu ayuda es grandiosa para poder completar las tareas, te envío un print screen de cada tarea que falta?Te parece?Mil gracias.

    El martes, 1 de diciembre de 2020 09:07:14 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 


@adelehk una pregunta, ¿Para la Clase 9 y 10, la Clase 11 y 12 y para la Clase 19 estas respuestas no les sirven?

Como ya dije antes, no tengo forma de saber de que las clases estén estructuradas de la misma forma para todos en el Playground, e incluso no me sorprendería si ustedes tienen ejercicios que yo nunca ví, y viceversa.

Del resto de las clases que no mencioné estoy seguro que no las tengo en el Playground, así que no sé qué piden los enunciados. No tengo problemas en resolver algunos para ustedes para que vean cómo se resuelven, aunque voy a necesitar que me pasen las consignas completas de cada actividad y cualquier cosa que incluya el editor de código. Si te interesa podés escribir los enunciados en comentarios separados así no se mezclan los ejercicios.

**Comment by Secreto31126** [comment]
Perfecto 👍

**Comment by adelehk** [comment]
Decime si esta bien asi?Muchas gracias.
    El martes, 1 de diciembre de 2020 11:14:04 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 


Perfecto 👍

**Comment by Secreto31126** [comment]
No hay ningún adjunto. Creo que si contestás desde el mail las imágenes no se agregan. Probá cargarla desde la página con la función adjuntar de GitHub.
![501st (Helmet)](https://user-images.githubusercontent.com/46955459/100753551-b2224c00-33c8-11eb-842a-9f2a5ff02187.png)

**Comment by adelehk** [comment]
Hola!!!!!!! te envio las demas, si podes ayudarme te super agradezco!!!!!!!!! 
    El martes, 1 de diciembre de 2020 11:14:04 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 


Perfecto 👍

**Comment by Secreto31126** [comment]
Sigo sin recibir ninguna imagen. Tenés que enviarlas desde [la web](https://github.com/Secreto31126/Digital-House-Answers/issues/1) para que me lleguen. Al final de la página hay un espacio para escribir, y si arrastrás las imágenes hasta el cuadrado se van a agregar para que las pueda ver.

**Comment by adelehk** [comment]
El martes, 1 de diciembre de 2020 11:52:50 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 


Sigo sin recibir ninguna imagen. Tenés que enviarlas desde la web para que me lleguen. Al final de la página hay un espacio para escribir, y si arrastrás las imágenes hasta el cuadrado se van a agregar para que las pueda ver.

**Comment by adelehk** [comment]
Hola, te paso los archivos! mil millones de gracias! Me da un poco de verguenza, son muchos! gracias.
[archive.zip](https://github.com/Secreto31126/Digital-House-Answers/files/5623863/archive.zip)

**Comment by Secreto31126** [comment]
Perfecto, hoy a la tarde noche me pongo a resolverlos y se los paso.

**Comment by adelehk** [comment]
Muchas gracias! no sabes que bien nos viene tu ayuda, :)

**Comment by adelehk** [comment]
Hola! te lo envie adjunto en paginas de word, lo tengo en enviados.Te lo re envio. Mil gracias!!!!!
    El martes, 1 de diciembre de 2020 11:52:50 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 


Sigo sin recibir ninguna imagen. Tenés que enviarlas desde la web para que me lleguen. Al final de la página hay un espacio para escribir, y si arrastrás las imágenes hasta el cuadrado se van a agregar para que las pueda ver.

**Comment by Secreto31126** [comment]
Hola de nuevo 👋

Creo que ya terminé con todas las consignas. Hay algunas que están un poco incompletas porque me faltaba algo de información, aunque me las arreglé para hacer tanto como pudiera. En algunos lugares dejé escrito lo que faltaba, o en casos especiales, indicaciones extras sobre cómo resolver los ejercicios. Si van siguiendo _atentamente_ las consignas y ayudándose con los códigos les debería salir fácilmente y van a empezar a entender cómo funcionan los programas.

[Digital House.zip](https://github.com/Secreto31126/Digital-House-Answers/files/5626479/Digital.House.zip)

Suerte con el fin de año, y si tienen cualquier duda pregúntenme ;)

P.D.: Si tienen problemas para abrir los archivos, hagan click con el botón derecho sobre el archivo > abrir con > block de notas, y ya les debería funcionar bien.

**Comment by adelehk** [comment]
Mil millones de gracias!Mañana lo veo!!!Sos muy buen chico.Te super agradezco, no me es fácil esto del html 😀Nuevamente te agradezco! Sos un genio.Gracias 👍🏻
    El martes, 1 de diciembre de 2020 22:54:44 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 


Hola de nuevo 👋
 
Creo que ya terminé con todas las consignas. Hay algunas que están un poco incompletas porque me faltaba algo de información, aunque me las arreglé para hacer tanto como pudiera. En algunos lugares dejé escrito lo que faltaba o en casos especiales cómo resolver los ejercicios. Si van siguiendo atentamente las consignas y ayudándose con los códigos les debería salir fácilmente y van a empezar a entender cómo funcionan los programas.

Digital House.zip

Suerte con el fin de año, y si tienen cualquier duda pregúntenme ;)

P.D.: Si tienen problemas para abrir los archivos, hagan click con el botón derecho sobre el archivo > abrir con > block de notas, y ya les debería funcionar bien.

**Comment by adelehk** [comment]
Hola1 Como estas? me re sirvio todo!!!! GENIO!!!!!No puedo insertar la foto del sitio web que tiene que hacer, la foto tengo que subirla en : Upload Image — Free Image Hosting, yo la

| 
| 
|  | 
Upload Image — Free Image Hosting

Free image hosting and sharing service, upload pictures, photo host. Offers integration solutions for uploading ...
 |

 |

 |

 subo, obtebgo un codigo, despues como lo inserto en el html???La consigna dice; 
Dentro del main coloca una imagen tuya debajo del título que dice Bienvenidos. (Si tienes la imagen en tu computadora primero deberás subirla a imgbb para obtener el enlace)

A la imagen colócale una clase con el nombre "miFoto"

Debajo de la imagen debes agregar un subtítulo con tu nombre
Pero la verdad que no queda insertada.... una ultima ayudita???Mil gracias!!!!!!!!!!!!!!
    El martes, 1 de diciembre de 2020 23:42:11 ART, Cyn <hacete_kargo@yahoo.com.ar> escribió:  
 
  Mil millones de gracias!Mañana lo veo!!!Sos muy buen chico.Te super agradezco, no me es fácil esto del html 😀Nuevamente te agradezco! Sos un genio.Gracias 👍🏻
    El martes, 1 de diciembre de 2020 22:54:44 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 


Hola de nuevo 👋
 
Creo que ya terminé con todas las consignas. Hay algunas que están un poco incompletas porque me faltaba algo de información, aunque me las arreglé para hacer tanto como pudiera. En algunos lugares dejé escrito lo que faltaba o en casos especiales cómo resolver los ejercicios. Si van siguiendo atentamente las consignas y ayudándose con los códigos les debería salir fácilmente y van a empezar a entender cómo funcionan los programas.

Digital House.zip

Suerte con el fin de año, y si tienen cualquier duda pregúntenme ;)

P.D.: Si tienen problemas para abrir los archivos, hagan click con el botón derecho sobre el archivo > abrir con > block de notas, y ya les debería funcionar bien.

**Comment by Secreto31126** [comment]
Es fácil, hay un tag que debe ser algo así:

<img src="EL LINK VA ACÁ, DENTRO DE LAS COMILLAS">

(Es posible que dentro de las comillas diga #Cambiar, es el método que uso
para que la gente encuentre fácilmente lo que deben cambiar)

**Comment by adelehk** [comment]
Si! ahi pude, pero ahora me da el error:    
   - Debes agregar una imagen tuya y colocarle la clase "miFoto"
Gracias!
    El miércoles, 2 de diciembre de 2020 11:14:34 ART, Cyn <hacete_kargo@yahoo.com.ar> escribió:  
 
  Hola1 Como estas? me re sirvio todo!!!! GENIO!!!!!No puedo insertar la foto del sitio web que tiene que hacer, la foto tengo que subirla en : Upload Image — Free Image Hosting, yo la

| 
| 
|  | 
Upload Image — Free Image Hosting

Free image hosting and sharing service, upload pictures, photo host. Offers integration solutions for uploading ...
 |

 |

 |

 subo, obtebgo un codigo, despues como lo inserto en el html???La consigna dice; 
Dentro del main coloca una imagen tuya debajo del título que dice Bienvenidos. (Si tienes la imagen en tu computadora primero deberás subirla a imgbb para obtener el enlace)

A la imagen colócale una clase con el nombre "miFoto"

Debajo de la imagen debes agregar un subtítulo con tu nombre
Pero la verdad que no queda insertada.... una ultima ayudita???Mil gracias!!!!!!!!!!!!!!
    El martes, 1 de diciembre de 2020 23:42:11 ART, Cyn <hacete_kargo@yahoo.com.ar> escribió:  
 
  Mil millones de gracias!Mañana lo veo!!!Sos muy buen chico.Te super agradezco, no me es fácil esto del html 😀Nuevamente te agradezco! Sos un genio.Gracias 👍🏻
    El martes, 1 de diciembre de 2020 22:54:44 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 


Hola de nuevo 👋
 
Creo que ya terminé con todas las consignas. Hay algunas que están un poco incompletas porque me faltaba algo de información, aunque me las arreglé para hacer tanto como pudiera. En algunos lugares dejé escrito lo que faltaba o en casos especiales cómo resolver los ejercicios. Si van siguiendo atentamente las consignas y ayudándose con los códigos les debería salir fácilmente y van a empezar a entender cómo funcionan los programas.

Digital House.zip

Suerte con el fin de año, y si tienen cualquier duda pregúntenme ;)

P.D.: Si tienen problemas para abrir los archivos, hagan click con el botón derecho sobre el archivo > abrir con > block de notas, y ya les debería funcionar bien.

**Comment by Secreto31126** [comment]
Me olvidé de la clase, también es fácil, al final debería quedarte algo así:

<img src="El Link de la Foto que ya agregaron" *class="miFoto"*>

**Comment by adelehk** [comment]
Tomas, perdon que te re moleste, pero cuando agrego esa info, la imagen sigue quedando grande sin bordes redondeados y queda debajo de la misma: este texto: " class="miFoto">
NO se que hacer!
Gracias
    El miércoles, 2 de diciembre de 2020 11:45:16 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 

Me olvidé de la clase, también es fácil, al final debería quedarte algo así:

<img src="El Link de la Foto que ya agregaron" *class="miFoto"*>

**Comment by Secreto31126** [comment]
No sé de dónde salieron los asteríscos, debía ser una letra en negrita.
Solo tenés que borrarlos y listo. Perdón que les haga dar tantas vueltas
por pequeños errores 🙃.

**Comment by adelehk** [comment]
No me pidas disculpas!!!!!!!Sos re buen chico y me estas re ayudando!Mil gracias.
    El miércoles, 2 de diciembre de 2020 13:15:57 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 

No sé de dónde salieron los asteríscos, debía ser una letra en negrita.
Solo tenés que borrarlos y listo. Perdón que les haga dar tantas vueltas
por pequeños errores 🙃.

**Comment by adelehk** [comment]
Otra vez...... te molesto
en este ejercicio:

Debajo del código que escribiste en la clase anterior continúa trabajando en tu HTML


Crea un subtítulo h3 que diga "Mis amigos son"

Crea una caja y dale una clase con el nombre "misAmigos"

Dentro de la caja con la clase "misAmigos" crea 3 cajas más y dale el nombre "amigo"

Dentro de cada caja con el nombre "amigo" agrega la imagen de un amigo/a tuyo. (Debes tener 3 fotos de amigos)

Debajo de cada imagen que agregaste, crea un párrafo diciendo quién es tu amigo/a. (Debes tener 3 párrafos debajo de las fotos)
No puedo hacer que me queden las tres imagenes una al lado de la otra, me queda una debajo de la otra. que puede ser??? :( Gracias
    El miércoles, 2 de diciembre de 2020 13:21:06 ART, Cyn <hacete_kargo@yahoo.com.ar> escribió:  
 
  No me pidas disculpas!!!!!!!Sos re buen chico y me estas re ayudando!Mil gracias.
    El miércoles, 2 de diciembre de 2020 13:15:57 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 

No sé de dónde salieron los asteríscos, debía ser una letra en negrita.
Solo tenés que borrarlos y listo. Perdón que les haga dar tantas vueltas
por pequeños errores 🙃.

**Comment by Secreto31126** [comment]
Eso no es lo que pide la consigna igualmente. Obviamente es posible hacerlo
(a la clase misAmigos le podés poner display: inline; en el CSS y las fotos
reducirle el tamaño para que se vea bien), pero por la forma que funciona
Playground es muy probable que el código te de un error de no cumplir lo
pedido.

Les dejo el código para el CSS por si les interesa saberlo:

.misAmigos {
  display: inline; /* Este comando hace que todas las cosas dentro de la
caja (fotos y textos) aparezcan una a lado de la otra */
}

.amigo img {
  width: 50%;
}

**Comment by adelehk** [comment]
Mil gracias por todo!Que tengas muchas felicidades!Saludos. 
    El miércoles, 2 de diciembre de 2020 18:35:16 ART, Tomás Raiti <notifications@github.com> escribió:  
 
 

Eso no es lo que pide la consigna igualmente. Obviamente es posible hacerlo
(a la clase misAmigos le podés poner display: inline; en el CSS y las fotos
reducirle el tamaño para que se vea bien), pero por la forma que funciona
Playground es muy probable que el código te de un error de no cumplir lo
pedido.

Les dejo el código para el CSS por si les interesa saberlo:

.misAmigos {
 display: inline; /* Este comando hace que todas las cosas dentro de la
caja (fotos y textos) aparezcan una a lado de la otra */
}

.amigo img {
 width: 50%;
}
